---
title: "Weight of Fish"
author: "Karen Hernandez"
date: "Year 2020"
output: 
  html_document:
    number_sections: true
    toc: true
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

## Build the best regression model you can that predicts the weight of perch
## Using only two predictor variables  


# Perch Model

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

```{r}
# read in the fish data 
fishdata <- read.csv(file="Fish.csv", header=TRUE)
PerchData <- filter(fishdata,Species=="Perch") %>% select(-Species)
```


#Bream Model

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Smelt Model


# Discussion and Final Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
